site_name: Remark42
site_url: https://remark42.com/
site_author: Umputun
site_description: >-
  Remark42 is a self-hosted, lightweight, and simple (yet functional) comment engine, which doesn't spy on users. 
  It can be embedded into blogs, articles or any other place where readers add comments.

repo_name: umputun/remark42
repo_url: https://github.com/umputun/remark42
copyright: Some rights reserved &copy; 2020 - 2022 Umputun

theme:
  name: material
  favicon: assets/favicon.ico
#  logo: assets/android-chrome-512x512.png
  language: en
  palette:
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - toc.follow
    - toc.integrate
    - content.code.annotate
    - content.tooltips
    - navigation.instant
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.suggest
plugins:
  - search
  - minify:
      minify_html: true

extra:
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/umputun
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/umputun/remark42/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/umputun

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Getting started:
    - Installation: getting-started/installation.md
  - Setup:
    - Frontend:
      - Setup: configuration/frontend/index.md
      - SPA: configuration/frontend/spa.md
    - CLI Parameters: configuration/parameters/index.md
    - Authorization: configuration/authorization/index.md
    - Notifications: configuration/notifications/index.md
    - Email: configuration/email/index.md
    - Telegram: configuration/telegram/index.md
    - Manuals:
      - Admin UI: manuals/admin-interface/index.md
      - Without subdomain: manuals/subdomain/index.md
      - On a separate domain: manuals/separate-domain/index.md
      - With Reproxy: manuals/reproxy/index.md
      - With Nginx: manuals/nginx/index.md
      - On Kubernetes: manuals/kubernetes/index.md
      - Gatsby Integration: manuals/integration-with-gatsby/index.md
    - Backup:
      - Backup: backup/backup.md
      - Restore: backup/restore.md
      - Migration: backup/migration.md
      - Site URL migration: backup/url-migration.md
    - Contributing:
      - Backend: contributing/backend.md
      - Frontend: contributing/frontend.md
      - Translations: contributing/translations.md
      - API: contributing/api.md
